// Plots charts for report
$(function() {
  $('#chart-reporting-sites').highcharts(
    sitesBarChart(
      reportingSites.categories,
      reportingSites.series,
      reportingSites.labels
    ));
  $('#chart-demographics').highcharts(
    genderBarChart(
      demographicsAges.categories,
      demographicsAges.series,
      demographicsAges.labels
    ));
  $('#chart-nationality').highcharts(
    pieChart(nationality)
  );
  $('#chart-status').highcharts(
    pieChart(patientStatus)
  );
  $('#chart-mor-communicable-disease').highcharts(
    pieChart(communicableDiseases)
  );
  $('#chart-mor-non-communicable-disease').highcharts(
    pieChart(nonCommunicableDiseases)
  );
  $('#chart-mental-health').highcharts(
    pieChart(mentalHealthConditions)
  );
  $('#chart-child-health').highcharts(
    pieChart(childHealthConditions)
  );
  $('#chart-mental-health-gender').highcharts(
    pieChart(mentalHealthConditionsGender)
  );
  $('#chart-mental-health-age').highcharts(
    pieChart(mentalHealthConditionsAge)
  );
  $('#chart-child-health-gender').highcharts(
    pieChart(childHealthConditionsGender)
  );
});
