var cdData = {
    "cmd_1": {
        "weeks": {},
        "year": 0
    },
    "cmd_10": {
        "weeks": {},
        "year": 0
    },
    "cmd_11": {
        "weeks": {},
        "year": 0
    },
    "cmd_12": {
        "weeks": {
            "9": 1.0
        },
        "year": 1.0
    },
    "cmd_13": {
        "weeks": {
            "11": 1.0,
            "12": 1.0
        },
        "year": 2.0
    },
    "cmd_14": {
        "weeks": {
            "6": 3.0,
            "7": 1.0,
            "10": 1.0,
            "12": 1.0
        },
        "year": 6.0
    },
    "cmd_15": {
        "weeks": {
            "6": 1.0
        },
        "year": 1.0
    },
    "cmd_16": {
        "weeks": {},
        "year": 0
    },
    "cmd_17": {
        "weeks": {},
        "year": 0
    },
    "cmd_18": {
        "weeks": {
            "9": 1.0,
            "10": 1.0,
            "12": 2.0,
            "13": 1.0
        },
        "year": 5.0
    },
    "cmd_19": {
        "weeks": {
            "2": 1.0,
            "9": 1.0
        },
        "year": 2.0
    },
    "cmd_2": {
        "weeks": {
            "9": 1.0
        },
        "year": 1.0
    },
    "cmd_20": {
        "weeks": {
            "1": 1.0,
            "2": 1.0,
            "4": 1.0,
            "5": 2.0,
            "6": 2.0,
            "7": 1.0,
            "8": 2.0,
            "9": 3.0,
            "10": 4.0,
            "11": 5.0,
            "12": 1.0
        },
        "year": 23.0
    },
    "cmd_21": {
        "weeks": {
            "1": 1.0,
            "2": 5.0,
            "3": 4.0,
            "4": 4.0,
            "5": 4.0,
            "6": 1.0,
            "7": 4.0,
            "8": 3.0,
            "9": 3.0,
            "10": 8.0,
            "11": 11.0,
            "12": 4.0,
            "13": 5.0
        },
        "year": 57.0
    },
    "cmd_22": {
        "weeks": {},
        "year": 0
    },
    "cmd_23": {
        "weeks": {},
        "year": 0
    },
    "cmd_24": {
        "weeks": {},
        "year": 0
    },
    "cmd_25": {
        "weeks": {},
        "year": 0
    },
    "cmd_26": {
        "weeks": {
            "1": 63.0,
            "2": 65.0,
            "3": 31.0,
            "4": 45.0,
            "5": 38.0,
            "6": 31.0,
            "7": 33.0,
            "8": 49.0,
            "9": 49.0,
            "10": 32.0,
            "11": 67.0,
            "12": 52.0,
            "13": 58.0
        },
        "year": 613.0
    },
    "cmd_27": {
        "weeks": {
            "1": 2.0,
            "2": 3.0,
            "4": 1.0,
            "7": 2.0,
            "8": 1.0,
            "9": 4.0,
            "11": 2.0,
            "12": 5.0,
            "13": 2.0
        },
        "year": 22.0
    },
    "cmd_28": {
        "weeks": {
            "4": 1.0,
            "8": 1.0,
            "10": 1.0,
            "11": 2.0,
            "12": 4.0
        },
        "year": 9.0
    },
    "cmd_29": {
        "weeks": {
            "1": 1.0,
            "2": 3.0,
            "3": 2.0,
            "4": 8.0,
            "5": 2.0,
            "6": 4.0,
            "7": 3.0,
            "8": 3.0,
            "9": 6.0,
            "10": 6.0,
            "11": 5.0,
            "12": 3.0,
            "13": 3.0
        },
        "year": 49.0
    },
    "cmd_3": {
        "weeks": {
            "1": 4.0,
            "2": 3.0,
            "3": 3.0,
            "4": 2.0,
            "5": 5.0,
            "6": 1.0,
            "7": 1.0,
            "8": 3.0,
            "9": 8.0,
            "10": 4.0,
            "11": 2.0,
            "12": 5.0,
            "13": 5.0
        },
        "year": 46.0
    },
    "cmd_30": {
        "weeks": {
            "1": 1.0,
            "2": 2.0,
            "5": 1.0,
            "7": 1.0,
            "9": 1.0
        },
        "year": 6.0
    },
    "cmd_31": {
        "weeks": {
            "6": 1.0
        },
        "year": 1.0
    },
    "cmd_32": {
        "weeks": {},
        "year": 0
    },
    "cmd_33": {
        "weeks": {},
        "year": 0
    },
    "cmd_34": {
        "weeks": {},
        "year": 0
    },
    "cmd_35": {
        "weeks": {
            "1": 3.0,
            "2": 3.0,
            "3": 2.0,
            "4": 2.0,
            "5": 3.0,
            "6": 4.0,
            "7": 1.0,
            "8": 2.0,
            "9": 2.0,
            "11": 1.0,
            "12": 4.0,
            "13": 3.0
        },
        "year": 30.0
    },
    "cmd_36": {
        "weeks": {},
        "year": 0
    },
    "cmd_37": {
        "weeks": {},
        "year": 0
    },
    "cmd_38": {
        "weeks": {
            "1": 3.0,
            "2": 3.0,
            "3": 15.0,
            "4": 5.0,
            "5": 1.0,
            "6": 1.0,
            "7": 3.0,
            "8": 3.0,
            "9": 8.0,
            "10": 3.0,
            "11": 1.0,
            "12": 1.0,
            "13": 2.0
        },
        "year": 49.0
    },
    "cmd_39": {
        "weeks": {},
        "year": 0
    },
    "cmd_4": {
        "weeks": {
            "2": 8.0,
            "3": 1.0,
            "5": 5.0,
            "7": 3.0,
            "8": 4.0,
            "10": 7.0,
            "11": 1.0,
            "12": 1.0
        },
        "year": 30.0
    },
    "cmd_40": {
        "weeks": {
            "1": 6.0,
            "2": 16.0,
            "3": 3.0,
            "4": 12.0,
            "5": 9.0,
            "6": 3.0,
            "8": 2.0,
            "9": 38.0,
            "10": 15.0,
            "11": 25.0,
            "12": 15.0,
            "13": 10.0
        },
        "year": 154.0
    },
    "cmd_41": {
        "weeks": {
            "6": 1.0
        },
        "year": 1.0
    },
    "cmd_42": {
        "weeks": {},
        "year": 0
    },
    "cmd_43": {
        "weeks": {},
        "year": 0
    },
    "cmd_44": {
        "weeks": {
            "6": 1.0,
            "9": 1.0,
            "12": 2.0
        },
        "year": 4.0
    },
    "cmd_45": {
        "weeks": {
            "1": 29.0,
            "2": 32.0,
            "3": 19.0,
            "4": 36.0,
            "5": 45.0,
            "6": 44.0,
            "7": 50.0,
            "8": 45.0,
            "9": 50.0,
            "10": 44.0,
            "11": 41.0,
            "12": 50.0,
            "13": 34.0
        },
        "year": 519.0
    },
    "cmd_46": {
        "weeks": {
            "1": 144.0,
            "2": 177.0,
            "3": 233.0,
            "4": 200.0,
            "5": 161.0,
            "6": 192.0,
            "7": 243.0,
            "8": 252.0,
            "9": 296.0,
            "10": 262.0,
            "11": 305.0,
            "12": 298.0,
            "13": 273.0
        },
        "year": 3036.0
    },
    "cmd_47": {
        "weeks": {
            "1": 29.0,
            "2": 34.0,
            "3": 10.0,
            "4": 35.0,
            "5": 16.0,
            "6": 19.0,
            "7": 14.0,
            "8": 14.0,
            "9": 11.0,
            "10": 12.0,
            "11": 19.0,
            "12": 17.0,
            "13": 7.0
        },
        "year": 237.0
    },
    "cmd_48": {
        "weeks": {
            "1": 1.0,
            "2": 2.0,
            "3": 3.0,
            "5": 1.0,
            "7": 1.0,
            "8": 1.0
        },
        "year": 9.0
    },
    "cmd_5": {
        "weeks": {
            "2": 1.0,
            "5": 1.0,
            "9": 1.0,
            "12": 1.0
        },
        "year": 4.0
    },
    "cmd_6": {
        "weeks": {},
        "year": 0
    },
    "cmd_7": {
        "weeks": {},
        "year": 0
    },
    "cmd_8": {
        "weeks": {
            "1": 3.0,
            "2": 2.0,
            "3": 1.0,
            "4": 4.0,
            "5": 1.0,
            "6": 3.0,
            "7": 5.0,
            "8": 1.0,
            "9": 3.0,
            "10": 7.0,
            "11": 5.0,
            "12": 2.0,
            "13": 4.0
        },
        "year": 41.0
    },
    "cmd_9": {
        "weeks": {},
        "year": 0
    }
};

var cdVariables = {
    "cmd_1": {
        "alert": 1,
        "alert_desc": "Group A",
        "alert_type": "individual",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description \nAn illness that is characterized by acute painless watery diarrhoea with or without vomiting. \n\nProbable case\nAny person 5 years or older with severe dehydration or death caused by acute diarrhoea (3 or more abnormally loose or fluid stools in the past 24 hours). Any person 2 years or older with acute diarrhoea (3 or more abnormally loose or fluid stools in the past 24 hours), with or without dehydration in an area where there is a cholera outbreak.\n\nConfirmed case \nA clinically compatible illness fulfilling the laboratory criterion.",
        "category": [
            "cd_tab",
            "Intestinal infectious diseases"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "A00,A00.0,A00.1,A00.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_1",
        "id_pk": 82,
        "labs_diagnostics": "Isolation of vibrio cholera 01 or 0139 from stool sample (at least 5 grams or pea sized) or rectal swab",
        "method": "match",
        "multiple_link": "",
        "name": "Cholera",
        "risk_factors": "Contaminated water sources, contaminated food sources, cholera outbreak, low environmental sanitation",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Watery diarrhea (3 or more abnormally loose or fluid stools in the past 24 hours, \"rice-water\" stool with or without vomiting), severe dehydration (including any of the following loss of skin turgor, malaise, tachypnoea, hypotension), fever (more cdon in children)",
        "type": "case"
    },
    "cmd_10": {
        "alert": 0,
        "alert_desc": "Group B",
        "alert_type": "",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description  \nTetanus is characterized by acute onset of hypertonia and/or painful muscular contractions, usually of the muscles of the jaw and neck, and generalized muscle spasms without other apparent medical cause.  \n\nProbable case\nA person with at least one of the following signs: inability to open the mouth or sustained spasm of the facial muscles; OR painful muscular contractions. Tetanus requires an injury or wound, but patients may be unable to recall a specific event.\n  \nConfirmed case \nA clinically compatible case as reported by a healthcare professional. ",
        "category": [
            "cd_tab",
            "Other bacterial diseases"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "A33,A34,A35",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_10",
        "id_pk": 91,
        "labs_diagnostics": "Not applicable.  The organism is rarely recovered from the site of infection and usually there is no detectable antibody response.",
        "method": "match",
        "multiple_link": "",
        "name": "Tetanus",
        "risk_factors": "Injury or wound, potential unsterile cord cutting (pregnant women during delivery)",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Inability to open mouth, sustained spasm of the facial muscles including the jaw, painful muscular contractions, inability to breastfeed (newborn), stiff body or arch (newborn), inability to breathe",
        "type": "case"
    },
    "cmd_11": {
        "alert": 1,
        "alert_desc": "Group A",
        "alert_type": "individual",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description \nAn upper respiratory tract illness characterized by sore throat, low-grade fever, and adherent membrane of the tonsil(s), pharynx, and/or nose without other apparent cause\n\nProbable case\nA clinically compatible illness.\n\nConfirmed case \nA clinically compatible illness that is EITHER  \n\u2022 Laboratory confirmed; OR \n\u2022 Epidemiologically linked to a confirmed case ",
        "category": [
            "cd_tab",
            "Other bacterial diseases"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "A36,A36.0,A36.1,A36.2,A36.3,A36.8,A36.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_11",
        "id_pk": 92,
        "labs_diagnostics": "",
        "method": "match",
        "multiple_link": "",
        "name": "Diphtheria",
        "risk_factors": "Exposure to a case of diphtheria",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Fever, Running nose, Cough, Adherent membrane (tough, grayish-white color) of the nose, pharynx, tonsils or larynx, Inflammation of cervical lymph nodes and surrounding tissue",
        "type": "case"
    },
    "cmd_12": {
        "alert": 1,
        "alert_desc": "Group A",
        "alert_type": "individual",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description \nA cough illness lasting at least 2 weeks with one of the following: paroxysms of coughing, inspiratory \u00e2\u20ac\u0153whoop\u00e2\u20ac\u009d, or post-tussive vomiting, and without other apparent causes. \n\nProbable case\nA case that meets the clinical description, but is not laboratory confirmed, and is not epidemiologically-linked to a laboratory confirmed case. \n\nConfirmed case \nAny one of the following: \n\u2022 An acute cough illness of any duration associated with B. pertussis isolation or positive PCR for B. pertussis  \n\u2022 A case that meets the clinical description and is epidemiologically-linked to a case confirmed by either culture or PCR.",
        "category": [
            "cd_tab",
            "Other bacterial diseases"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "A37,A37.0,A37.1,A37.8,A37.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_12",
        "id_pk": 93,
        "labs_diagnostics": "\u2022 Isolation of Bordetella pertussis from a clinical specimen, or  \n\u2022 Positive polymerase chain reaction (PCR) assay for B. pertussis ",
        "method": "match",
        "multiple_link": "",
        "name": "Whooping cough",
        "risk_factors": "Exposure to a case of pertussis",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Cough lasting at least 2 weeks, paroxysms of coughing, inspiratory whoop,posttussive vomiting",
        "type": "case"
    },
    "cmd_13": {
        "alert": 1,
        "alert_desc": "Group A",
        "alert_type": "individual",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "International Classification of Disease (ICD-10)",
        "category": [
            "cd_tab",
            "Other bacterial diseases"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "A38",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_13",
        "id_pk": 94,
        "labs_diagnostics": "",
        "method": "match",
        "multiple_link": "",
        "name": "Scarlet fever",
        "risk_factors": "",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "",
        "type": "case"
    },
    "cmd_14": {
        "alert": 0,
        "alert_desc": "Group B",
        "alert_type": "",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description  \nAn acute bacterial disease, characterized by sudden onset of fever (>38.0 degrees Celsius axillary or >38.5 degrees Celsius rectal) AND ONE of the following signs: neck stiffness; altered consciousness; petechial or purpural rash, or other meningeal signs. In children <1 year, meningitis is suspected when fever is accompanied by a bulging fontanelle.\n\nProbable case  \nA clinically compatible illness with Gram-negative diplococci identified in any sterile fluids such as CSF.\n\nConfirmed case \n A clinically compatible case that is laboratory confirmed",
        "category": [
            "cd_tab",
            "Other bacterial diseases"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "A39,A39.0,A39.1,A39.2,A39.3,A39.4,A39.5,A39.8,A39.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_14",
        "id_pk": 95,
        "labs_diagnostics": "Conduct lumbar puncture of first 25 cases during an epidemic to confirm diagnosis and serogroup",
        "method": "match",
        "multiple_link": "",
        "name": "Meningitis",
        "risk_factors": "Close and prolonged contact with individual suspected of having meningitis, High rates of acute respiratory infection (ARI), Overcrowding conditions, Other",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Sudden onset of intense headache, Suddepn onset of fever, Sudden onset of nausea, Sudden onset of vomiting, Sudden onset of photophobia, Sudden onset of stiff neck, Lethargy, Delirium, Coma, Purpura, Shock symptoms, Other",
        "type": "case"
    },
    "cmd_15": {
        "alert": 0,
        "alert_desc": "Group B",
        "alert_type": "",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "International Classification of Disease (ICD-10)",
        "category": [
            "cd_tab",
            "Infections with a predominantly sexual mode of transmission"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "A53,A53.0,A53.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_15",
        "id_pk": 96,
        "labs_diagnostics": "",
        "method": "match",
        "multiple_link": "",
        "name": "Syphilis",
        "risk_factors": "",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "",
        "type": "case"
    },
    "cmd_16": {
        "alert": 0,
        "alert_desc": "Group B",
        "alert_type": "",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "International Classification of Disease (ICD-10)",
        "category": [
            "cd_tab",
            "Infections with a predominantly sexual mode of transmission"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "A54,A54.0,A54.1,A54.2,A54.3,A54.4,A54.5,A54.6,A54.8,A54.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_16",
        "id_pk": 97,
        "labs_diagnostics": "",
        "method": "match",
        "multiple_link": "",
        "name": "Gonorrhoea",
        "risk_factors": "",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "",
        "type": "case"
    },
    "cmd_17": {
        "alert": 1,
        "alert_desc": "Group A",
        "alert_type": "individual",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "International Classification of Disease (ICD-10)",
        "category": [
            "cd_tab",
            "Other spirochaetal diseases"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "A68,A68.0,A68.1,A68.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_17",
        "id_pk": 98,
        "labs_diagnostics": "",
        "method": "match",
        "multiple_link": "",
        "name": "Relapsing fevers",
        "risk_factors": "",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "",
        "type": "case"
    },
    "cmd_18": {
        "alert": 0,
        "alert_desc": "Group B",
        "alert_type": "",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description\nRickettsial diseases are caused by a group of Gram-negative obligate intracellular bacteria in the family Rickettsiaceae. They are primarily vector-borne diseases \u00e2\u20ac\u201c transmitted by the bite or faeces of infected arthropod vectors.  \n\nThe affected patients usually presents sudden headache, chills, high fever, prostration, coughing and severe muscular pain. After 5 to 6 days, a macular skin eruption (dark spots) develop on the upper trunk and spreads to the rest of the body.\n\nProbable case \nA clinically compatible case with supportive laboratory findings: \nImmunofluorescence test demonstrating a single antibody titre against Typhus group \u00e2\u2030\u00a5 512 \n\nConfirmed case \n A clinically compatible case that is laboratory confirmed.",
        "category": [
            "cd_tab",
            "Rickettsioses"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "A75,A75.0,A75.1,A75.2,A75.3,A75.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_18",
        "id_pk": 99,
        "labs_diagnostics": "Any one of the following:  \n\u2022 Immunofluorescence test demonstrating a four-fold or greater increase in antibody titre against typhus group \n\u2022 Polymerase chain reaction assay demonstrating the presence of the genome of Rickettsia in the blood specimen",
        "method": "match",
        "multiple_link": "",
        "name": "Typhus fever",
        "risk_factors": "Cold, mountainous conditions, Overcrowded living conditions, Displacement, Exposure to lice",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Headache, Chills, High fever , Prostration, Coughing, Severe muscular pain, Macular skin eruption (dark spots) on upper trunk or other areas of the body)",
        "type": "case"
    },
    "cmd_19": {
        "alert": 0,
        "alert_desc": "Group A",
        "alert_type": "",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description\nAcute flaccid paralysis (AFP) is defined as acute onset of focal weakness or paralysis characterized as flaccid (reduced muscle tone).  The AFP surveillance has been set up primarily for detecting acute poliomyelitis among children under 15 years of age. \n\nProbable case\nAny child <15 years with acute flaccid paralysis including Guillain-Barre syndrome OR any paralytic illness in a person of any age OR a person of any age in whom the clinician suspects polio.",
        "category": [
            "cd_tab",
            "Viral infections of the central nervous system"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "A80,A80.0,A80.1,A80.2,A80.3,A80.4,A80.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_19",
        "id_pk": 100,
        "labs_diagnostics": "Stool sample taken 24 hours apart within 14 days of onset of paralysis",
        "method": "match",
        "multiple_link": "",
        "name": "Polio",
        "risk_factors": "Age (children under 5), contaminated water sources, another case of AFP reported in the same area",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Asymptomatic, fever, fatigue, headache, vomiting, stiffness in the neck, pain in limbs",
        "type": "case"
    },
    "cmd_2": {
        "alert": 0,
        "alert_desc": "Group B",
        "alert_type": "",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description \nAn illness characterized by insidious onset of sustained fever, headache, malaise, cough, bradycardia, splenomegaly or rose spot on the trunk with or without gastrointestinal symptoms. \n \nProbable case \nA clinically compatible case that EITHER  \n\u2022 Has Widal test result of titre of Salmonella Typhi O antibody of 200 or greater OR \n\u2022 Epidemiologically linked to a confirmed case. \n\nConfirmed case  \nA clinically compatible case with laboratory confirmation.",
        "category": [
            "cd_tab",
            "Intestinal infectious diseases"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "A01,A01.0,A01.1,A01.2,A01.3,A01.4",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_2",
        "id_pk": 83,
        "labs_diagnostics": "\u2022 Salmonella Typhi isolated from any clinical specimen \n\u2022 Widal test result of a four-fold or greater rise in the titre of Salmonella Typhi O antibody in paired sera ",
        "method": "match",
        "multiple_link": "",
        "name": "Typhoid fever",
        "risk_factors": "Work in or travel to areas where typhoid fever is endemic, close contact with someone who is infected or has recently been infected with typhoid fever, drink water contaminated by sewage that contains S. typhi",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Fever, headache, malaise, cough, bradycardia, splenomegaly, rose spot on the trunk, gastrointestinal symptoms",
        "type": "case"
    },
    "cmd_20": {
        "alert": 0,
        "alert_desc": "Group A",
        "alert_type": "",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description \nRabies is an acute encephalomyelitis that almost always progresses to coma or death within 10 days of the first symptoms.  Onset with headache, fever, malaise and sensory changes referred to the bite wound.  The disease progresses to paresis or paralysis, spasm of muscles of deglutition on attempts to swallow leads to fear of water (hydrophobia), delirium and convulsion.  Death is often due to respiratory paralysis.  \n\nProbable case \nA clinically compatible illness plus history of contact with a suspected rabid animal or epidemiologically linked to a confirmed case. \n\nConfirmed case \n A clinically compatible illness that is laboratory confirmed.",
        "category": [
            "cd_tab",
            "Viral infections of the central nervous system"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "A82,A82.0,A82.1,A82.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_20",
        "id_pk": 101,
        "labs_diagnostics": "Antigen detection using the FA test on skin biopsies from patients with clinical rabies, virus isolation using neuroblastoma cells (preferably performed on saliva samples or other biological fluids such as tears or cerebrospinal fluid), RFFIT or FAVN test antibody tests for non-vaccinated patients",
        "method": "match",
        "multiple_link": "",
        "name": "Rabies",
        "risk_factors": "Exposure to rabies-carrying vectors (e.g. bats, etc.)",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Spasms in response to tactile, auditory, visual or olfactory stimuli, Paralysis or Guillan-Barre-like syndrome, Myoedema at percussion sites, Encephalitis",
        "type": "case"
    },
    "cmd_21": {
        "alert": 0,
        "alert_desc": "Group B",
        "alert_type": "",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description  \nAn acute bacterial disease, characterized by sudden onset of fever (>38.0 degrees Celsius axillary or >38.5 degrees Celsius rectal) AND ONE of the following signs: neck stiffness; altered consciousness; petechial or purpural rash, or other meningeal signs. In children <1 year, meningitis is suspected when fever is accompanied by a bulging fontanelle.\n\nProbable case  \nA clinically compatible illness with Gram-negative diplococci identified in any sterile fluids such as CSF.\n\nConfirmed case \n A clinically compatible case that is laboratory confirmed",
        "category": [
            "cd_tab",
            "Viral infections of the central nervous system"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "A87,A87.0,A87.1,A87.2,A87.8,A87.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_21",
        "id_pk": 102,
        "labs_diagnostics": "Conduct lumbar puncture of first 25 cases during an epidemic to confirm diagnosis and serogroup",
        "method": "match",
        "multiple_link": "",
        "name": "Viral meningitis",
        "risk_factors": "Close and prolonged contact with individual suspected of having meningitis, High rates of acute respiratory infection (ARI), Overcrowding conditions, Other",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Sudden onset of intense headache, Suddepn onset of fever, Sudden onset of nausea, Sudden onset of vomiting, Sudden onset of photophobia, Sudden onset of stiff neck, Lethargy, Delirium, Coma, Purpura, Shock symptoms, Other",
        "type": "case"
    },
    "cmd_22": {
        "alert": 1,
        "alert_desc": "Group A",
        "alert_type": "individual",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description\nDengue fever is an acute febrile illness with two or more of the following symptoms: headache, retro-orbital pain, myalgia, arthralgia, rash, haemorrhagic manifestations, leukopenia or thrombocytopenia\n\nProbable case\nA clinically compatible case with supportive serology: \n\u2022 A positive IgM antibody test on a single serum specimen to dengue virus antigens; OR \n\u2022 Antibody titre of \u00e2\u2030\u00a5 1280 on a single serum specimen to one or more dengue virus antigens \n\nConfirmed case\nA clinically compatible case with laboratory confirmation.",
        "category": [
            "cd_tab",
            "Arthropod-borne viral fevers and viral haemorrhagic fevers"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "A90,A91",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_22",
        "id_pk": 103,
        "labs_diagnostics": "Any one of the following:  \n\u2022 Isolation of dengue virus from serum and/or autopsy samples \n\u2022 Demonstration of a four-fold or greater change in antibody titres to one or more dengue virus antigens in paired serum samples \n\u2022 Detection of dengue virus genomic sequences in autopsy tissue or serum samples by polymerase chain reaction (PCR) \n\u2022 Demonstration of dengue virus antigen in serum samples ",
        "method": "match",
        "multiple_link": "",
        "name": "Dengue Fever",
        "risk_factors": "Living or travelling in tropical areas, prior infection with a dengue fever virus",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Headache, retro-orbital pain, myalgia, arthralgia, rash, haemorrhagic manifestations, leukopenia or thrombocytopenia",
        "type": "case"
    },
    "cmd_23": {
        "alert": 1,
        "alert_desc": "Group A",
        "alert_type": "individual",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description \nA mosquito-borne viral illness characterized by acute onset and constitutional symptoms followed by brief remission and recurrence of fever, hepatitis, albuminuria, and in some instances, renal failure, shock, and generalized haemorrhages. \n\nProbable case \nA clinically compatible illness with supportive serology. (Stable elevated antibody titre to yellow fever virus, or a positive IgM result.  Cross-reactive serologic reactions to other flaviviruses must be ruled out, and there must be no history of yellow fever immunization.) \n\nConfirmed case\nA clinically compatible illness that is laboratory confirmed.  ",
        "category": [
            "cd_tab",
            "Arthropod-borne viral fevers and viral haemorrhagic fevers"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "A95,A95.0,A95.1,A95.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_23",
        "id_pk": 104,
        "labs_diagnostics": "\u2022 Four-fold or greater rise in yellow fever antibody titre with no history of recent yellow fever immunization, and cross-reactions to other flaviviruses ruled out; OR  \n\u2022 Demonstration of yellow fever virus, antigen, or genome in tissue, blood, or other body fluid  ",
        "method": "match",
        "multiple_link": "",
        "name": "Yellow fever",
        "risk_factors": "Travel to an area where mosquitoes continue to carry the yellow fever virus",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Fever, hepatitis, albuminuria, renal failure, shock, haemorrhage",
        "type": "case"
    },
    "cmd_24": {
        "alert": 1,
        "alert_desc": "Group A",
        "alert_type": "individual",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description \nViral haemorrhagic fever (VHF) refers to a group of systemic mild to life-threatening viral infection often complicated by haemorrhagic syndromes. Initial symptoms include marked fever, malaise, dizziness, myalgia, loss of strength, and exhaustion. Severe cases may show signs of bleeding under the skin, in internal organs, or from body orifices like the mouth, eyes, or ears. Some cases may even show shock, nervous system malfunction, coma, delirium, and seizures.  \n\nProbable case \nA clinically compatible case with any one of the following epidemiological evidence: \n\u2022 History of travel to an endemic/epidemic area within the incubation period of illness onset, or \n\u2022 Contact with a confirmed case, or \n\u2022 Exposure to viral haemorrhagic fever infected blood or tissues \n\nConfirmed case \nA case that is laboratory confirmed. ",
        "category": [
            "cd_tab",
            "Arthropod-borne viral fevers and viral haemorrhagic fevers"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "A98,A98.0,A98.1,A98.2,A98.3,A98.5,A98.8,A99",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_24",
        "id_pk": 105,
        "labs_diagnostics": "Any one of the following: \n\u2022 Isolation of a viral haemorrhagic fever virus from a clinical specimen \n\u2022 Detection of specific virus by nucleic acid testing (e.g. PCR), antigen detection assay, or electronic microscopy from a clinical specimen \n\u2022 IgG seroconversion or a fourfold or greater rise in titre to specific virus",
        "method": "match",
        "multiple_link": "",
        "name": "Viral haemorrhagic fever",
        "risk_factors": "Acute onset of fever, haemorrhagic or purpuric rash, bleeding from the nose, vomiting blood, coughing up blood, blood in stools, other haemorrhagic symptoms",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Reside in or move to an endemic area, exposure to vectors (ticks, rodents, livestock, mosquitoes, camels, horses etc.)",
        "type": "case"
    },
    "cmd_25": {
        "alert": 1,
        "alert_desc": "Group A",
        "alert_type": "individual",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description \nViral haemorrhagic fever (VHF) refers to a group of systemic mild to life-threatening viral infection often complicated by haemorrhagic syndromes. Initial symptoms include marked fever, malaise, dizziness, myalgia, loss of strength, and exhaustion. Severe cases may show signs of bleeding under the skin, in internal organs, or from body orifices like the mouth, eyes, or ears. Some cases may even show shock, nervous system malfunction, coma, delirium, and seizures.  \n\nProbable case \nA clinically compatible case with any one of the following epidemiological evidence: \n\u2022 History of travel to an endemic/epidemic area within the incubation period of illness onset, or \n\u2022 Contact with a confirmed case, or \n\u2022 Exposure to viral haemorrhagic fever infected blood or tissues \n\nConfirmed case \nA case that is laboratory confirmed. ",
        "category": [
            "cd_tab",
            "Arthropod-borne viral fevers and viral haemorrhagic fevers"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "A98.4",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_25",
        "id_pk": 106,
        "labs_diagnostics": "Any one of the following: \n\u2022 Isolation of a viral haemorrhagic fever virus from a clinical specimen \n\u2022 Detection of specific virus by nucleic acid testing (e.g. PCR), antigen detection assay, or electronic microscopy from a clinical specimen \n\u2022 IgG seroconversion or a fourfold or greater rise in titre to specific virus",
        "method": "match",
        "multiple_link": "",
        "name": "Ebola virus disease",
        "risk_factors": "Acute onset of fever, haemorrhagic or purpuric rash, bleeding from the nose, vomiting blood, coughing up blood, blood in stools, other haemorrhagic symptoms",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Reside in or move to an endemic area, exposure to vectors (ticks, rodents, livestock, mosquitoes, camels, horses etc.)",
        "type": "case"
    },
    "cmd_26": {
        "alert": 1,
        "alert_desc": "Group B",
        "alert_type": "threshold:3,5,6,10",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description \nAn illness with acute onset of diffuse (generalized) papulovesicular rash without other apparent cause. In vaccinated persons who develop chickenpox more than 42 days after vaccination (breakthrough disease), the disease is usually mild with fewer than 50 skin lesions and shorter duration of illness. The rash may also be atypical in appearance (maculopapular with few or no vesicles). \n\nProbable case \nA case that meets the typical clinical description, is not laboratory confirmed and is not epidemiologically linked to a confirmed case; OR \n\nConfirmed case \nA clinically compatible illness that is EITHER  \n\u2022 Laboratory confirmed; OR \n\u2022 Epidemiologically linked to a confirmed case",
        "category": [
            "cd_tab",
            "Viral infections characterized by skin and mucous membrane lesions"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "B01,B01.0,B01.1,B01.2,B01.8,B01.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_26",
        "id_pk": 107,
        "labs_diagnostics": "Any one of the following:  \n\u2022 Isolation of varicella zoster virus from a clinical specimen \n\u2022 Demonstration of four-fold or greater rise in antibody titre \n\u2022 Demonstration of viral antigen in vesicular scrapings using fluorescent-antibody staining \n\u2022 Positive PCR for varicella zoster virus in clinical specimen ",
        "method": "match",
        "multiple_link": "",
        "name": "Chicken pox",
        "risk_factors": "Direct contact with the symptomatic person with rash or by droplets dispersed into the air by coughing or sneezing",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "acute onset, diffuse (generalized) papulovesicular rash without other apparent cause",
        "type": "case"
    },
    "cmd_27": {
        "alert": 1,
        "alert_desc": "Group A",
        "alert_type": "individual",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description  \nAn illness characterised by all the following: \n\u2022 a generalized rash lasting \u00e2\u2030\u00a5 3 days, \n\u2022 a temperature \u00e2\u2030\u00a5 38.3oC and  \n\u2022 cough, coryza or conjunctivitis \n \nProbable case\nAny person with fever AND maculopapular (non-vesicular) rash AND ONE of the following: cough, runny nose or red eyes; OR any person in whom a clinician suspects measles. A measles death is a death occurring within 30 days of onset of the rash.\n\nConfirmed case \n\u2022 A case that is laboratory confirmed. A laboratory confirmed case does not need to meet the clinical case definition; OR \n\u2022 A clinically compatible case that is epidemiologically linked to a confirmed case",
        "category": [
            "cd_tab",
            "Viral infections characterized by skin and mucous membrane lesions"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "B05,B05.0,B05.1,B05.2,B05.3,B05.4,B05.8,B05.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_27",
        "id_pk": 108,
        "labs_diagnostics": "Any one of the following: \n\u2022 Positive serologic test for measles IgM antibody  \n\u2022 \u00e2\u2030\u00a5 four-fold increase in measles antibody titre  \n\u2022 Isolation of measles virus from a clinical specimen \n\u2022 PCR positive for measles virus in clinical specimen ",
        "method": "match",
        "multiple_link": "",
        "name": "Measles",
        "risk_factors": "Age (children between 9 months and 5 years), overcrowding conditions, measles immunization coverage rate known to be <80% in area of origin/residence, malnutrition",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "High fever, rash, runny nose, cough, conjunctivitis, Koplik spots (small white spots on buccal mucosa), red maculopapular (blotchy) rash 3 to 7 days after onset starting behind the ears and hairline",
        "type": "case"
    },
    "cmd_28": {
        "alert": 1,
        "alert_desc": "Group A",
        "alert_type": "individual",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description\nIn the absence of a more likely diagnosis, an illness characterized by all of the following:\n\u2022 Acute onset of generalized maculopapular rash; and\n\u2022 Temperature greater than 37.2\u00c2\u00b0 C, if measures; and\n\u2022 Anthralgia, arthritis, lymphadenopathy, or conjunctivitis; and\n\u2022 Lack of epidemiologic linkage to a laboratory-confirmed case of rubella; and noncontributory or no serologic or virologic testing.\n \nProbable case  \nA probable case of rubella is a case that meets the clinical description, and has no or non-contributory serologic or virologic testing, and is not epidemiologically linked to a laboratory confirmed case. \n\n Confirmed case \nA confirmed case of rubella is: \n\u2022 A case that is laboratory confirmed; OR  \n\u2022 A case that meets the clinical description and is epidemiologically linked to a confirmed case",
        "category": [
            "cd_tab",
            "Viral infections characterized by skin and mucous membrane lesions"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "B06,B06.0,B06.8,B06.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_28",
        "id_pk": 109,
        "labs_diagnostics": "Any of the following: \n\u2022 Isolation of rubella virus  \n\u2022 Positive serological test for rubella IgM antibody  \n\u2022 Positive PCR for rubella virus in clinical specimen \n\u2022 Four-fold increase between acute and convalescent phase titres in rubella antibody level by any standard serological assay; OR, for Congenital Rubella Syndrome, infant rubella antibody level that persists longer than expected from passive transfer of maternal antibody ",
        "method": "match",
        "multiple_link": "",
        "name": "Rubella",
        "risk_factors": "Exposure to individual with suspected rubella or cold-like symptoms and rash",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Low-grade fever, Headache, Malaise, Mild coryza, Conjunctivitis, Postauricular, occipital and posterior cervical lymphadenopathy, Rash, Arthralgia, Arthritis, Thrombocytopenic purpura, Encephalitis",
        "type": "case"
    },
    "cmd_29": {
        "alert": 1,
        "alert_desc": "Group B",
        "alert_type": "treshold:3,5",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description \nViral hepatitis is characterized by features of an acute infectious hepatitis including fever, malaise, anorexia, nausea, abdominal discomfort, dark urine, and jaundice. \n \nProbable case\nAny person with acute onset of jaundice (yellowing of whites of eyes or skin or dark/brown urine) AND severe illness with or without fever AND the absence of any known precipitating factors. Acute hepatitis often presents as acute jaundice syndrome.\n\nConfirmed case \nA clinically compatible illness with laboratory confirmation",
        "category": [
            "cd_tab",
            "Viral hepatitis"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "B15,B15.0,B15.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_29",
        "id_pk": 110,
        "labs_diagnostics": "Hepatitis A   anti-HAV IgM positive \nHepatitis B   IgM anti-HBc positive \nHepatitis C   anti-HCV or HCV-RNA PCR positive  \nHepatitis D   anti-HDV positive  \nHepatitis E  anti-HEV and anti-HEV IgM positive or HEV PCR positive ",
        "method": "match",
        "multiple_link": "",
        "name": "Hepatitis A",
        "risk_factors": "Endemic Hepatitis A, contaminated water sources, contaminated food sources",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Asymptomatic, jaundice, dark urine, anorexia, malaise, extreme fatigue, pain in upper right quadrant",
        "type": "case"
    },
    "cmd_3": {
        "alert": 0,
        "alert_desc": "Group B",
        "alert_type": "",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description\nAn illness of variable severity characterized by diarrhoea (with blood, mucus or pus), fever, nausea, vomiting, abdominal cramps and tenesmus. \n\nProbable case\nA clinically compatible case without laboratory confirmation, but is epidemiologically linked to a confirmed case.  \n\nConfirmed case \nA clinically compatible case with laboratory confirmation. ",
        "category": [
            "cd_tab",
            "Intestinal infectious diseases"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "A03,A03.0,A03.1,A03.2,A03.3,A03.8,A03.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_3",
        "id_pk": 84,
        "labs_diagnostics": "Isolation of Shigella dysenteriae type 1 from stool samples (at least 5 grams or pea sized)",
        "method": "match",
        "multiple_link": "",
        "name": "Bloody diarrhoea",
        "risk_factors": "Contaminated water, contaminated food, malnourished, age (children under 5, older adults), children who have had measles in past 6 weeks, shigellosis outbreak",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Malnourished, bloody diarrhea (3 or more abnormally loose or fluid stools in past 24 hours with visible blood), fever, abdominal cramps, rectal pain, seizures, sepsis, rectal prolapsed, toxic megacolon, hemolytic uraemic syndrome",
        "type": "case"
    },
    "cmd_30": {
        "alert": 0,
        "alert_desc": "Group B",
        "alert_type": "",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description \nViral hepatitis is characterized by features of an acute infectious hepatitis including fever, malaise, anorexia, nausea, abdominal discomfort, dark urine, and jaundice. \n \nProbable case\nAny person with acute onset of jaundice (yellowing of whites of eyes or skin or dark/brown urine) AND severe illness with or without fever AND the absence of any known precipitating factors. Acute hepatitis often presents as acute jaundice syndrome.\n\nConfirmed case \nA clinically compatible illness with laboratory confirmation",
        "category": [
            "cd_tab",
            "Viral hepatitis"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "B16,B16.0,B16.1,B16.2,B16.9,B17.0,B18.0,B18.1",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_30",
        "id_pk": 111,
        "labs_diagnostics": "Hepatitis A   anti-HAV IgM positive \nHepatitis B   IgM anti-HBc positive \nHepatitis C   anti-HCV or HCV-RNA PCR positive  \nHepatitis D   anti-HDV positive  \nHepatitis E  anti-HEV and anti-HEV IgM positive or HEV PCR positive ",
        "method": "match",
        "multiple_link": "",
        "name": "Hepatitis B",
        "risk_factors": "Endemic Hepatitis A, contaminated water sources, contaminated food sources",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Asymptomatic, jaundice, dark urine, anorexia, malaise, extreme fatigue, pain in upper right quadrant",
        "type": "case"
    },
    "cmd_31": {
        "alert": 0,
        "alert_desc": "Group B",
        "alert_type": "",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description \nViral hepatitis is characterized by features of an acute infectious hepatitis including fever, malaise, anorexia, nausea, abdominal discomfort, dark urine, and jaundice. \n \nProbable case\nAny person with acute onset of jaundice (yellowing of whites of eyes or skin or dark/brown urine) AND severe illness with or without fever AND the absence of any known precipitating factors. Acute hepatitis often presents as acute jaundice syndrome.\n\nConfirmed case \nA clinically compatible illness with laboratory confirmation",
        "category": [
            "cd_tab",
            "Viral hepatitis"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "B17.1,B18.2",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_31",
        "id_pk": 112,
        "labs_diagnostics": "Hepatitis A   anti-HAV IgM positive \nHepatitis B   IgM anti-HBc positive \nHepatitis C   anti-HCV or HCV-RNA PCR positive  \nHepatitis D   anti-HDV positive  \nHepatitis E  anti-HEV and anti-HEV IgM positive or HEV PCR positive ",
        "method": "match",
        "multiple_link": "",
        "name": "Hepatitis C",
        "risk_factors": "Endemic Hepatitis A, contaminated water sources, contaminated food sources",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Asymptomatic, jaundice, dark urine, anorexia, malaise, extreme fatigue, pain in upper right quadrant",
        "type": "case"
    },
    "cmd_32": {
        "alert": 0,
        "alert_desc": "Group B",
        "alert_type": "",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description \nViral hepatitis is characterized by features of an acute infectious hepatitis including fever, malaise, anorexia, nausea, abdominal discomfort, dark urine, and jaundice. \n \nProbable case\nAny person with acute onset of jaundice (yellowing of whites of eyes or skin or dark/brown urine) AND severe illness with or without fever AND the absence of any known precipitating factors. Acute hepatitis often presents as acute jaundice syndrome.\n\nConfirmed case \nA clinically compatible illness with laboratory confirmation",
        "category": [
            "cd_tab",
            "Viral hepatitis"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "B17.2",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_32",
        "id_pk": 113,
        "labs_diagnostics": "Hepatitis A   anti-HAV IgM positive \nHepatitis B   IgM anti-HBc positive \nHepatitis C   anti-HCV or HCV-RNA PCR positive  \nHepatitis D   anti-HDV positive  \nHepatitis E  anti-HEV and anti-HEV IgM positive or HEV PCR positive ",
        "method": "match",
        "multiple_link": "",
        "name": "Hepatitis E",
        "risk_factors": "Endemic Hepatitis A, contaminated water sources, contaminated food sources",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Asymptomatic, jaundice, dark urine, anorexia, malaise, extreme fatigue, pain in upper right quadrant",
        "type": "case"
    },
    "cmd_33": {
        "alert": 0,
        "alert_desc": "Group B",
        "alert_type": "",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description \nViral hepatitis is characterized by features of an acute infectious hepatitis including fever, malaise, anorexia, nausea, abdominal discomfort, dark urine, and jaundice. \n \nProbable case\nAny person with acute onset of jaundice (yellowing of whites of eyes or skin or dark/brown urine) AND severe illness with or without fever AND the absence of any known precipitating factors. Acute hepatitis often presents as acute jaundice syndrome.\n\nConfirmed case \nA clinically compatible illness with laboratory confirmation",
        "category": [
            "cd_tab",
            "Viral hepatitis"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "B17.8,B17.9,B18.8,B18.9,B19.0,B19.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_33",
        "id_pk": 114,
        "labs_diagnostics": "Hepatitis A   anti-HAV IgM positive \nHepatitis B   IgM anti-HBc positive \nHepatitis C   anti-HCV or HCV-RNA PCR positive  \nHepatitis D   anti-HDV positive  \nHepatitis E  anti-HEV and anti-HEV IgM positive or HEV PCR positive ",
        "method": "match",
        "multiple_link": "",
        "name": "Hepatitis (Unspecificed)",
        "risk_factors": "Endemic Hepatitis A, contaminated water sources, contaminated food sources",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Asymptomatic, jaundice, dark urine, anorexia, malaise, extreme fatigue, pain in upper right quadrant",
        "type": "case"
    },
    "cmd_34": {
        "alert": 1,
        "alert_desc": "Group A",
        "alert_type": "individual",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description: \n\u2022 For adults and children 18 months and older, persons have a positive HIV antibody test (rapid or laboratory-based enzyme immunoassay) confirmed by a second HIV antibody test (rapid or laboratory-based enzyme immunoassay) relying on different antigens or of different operating characteristics. \n\n\u2022 For children younger than 18 months, a positive virological test for HIV or its components (HIV-RNA or HIV-DNA or ultrasensitive HIV p24 antigen) confirmed by a second virological test obtained from a separate determination taken more than 4 weeks after birth. Clinical staging is utilized to establish stage of HIV infection.",
        "category": [
            "cd_tab",
            "Human immunodeficiency virus [HIV] disease"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "B20,B20.0,B20.1,B20.2,B20.3,B20.4,B20.5,B20.6,B20.7,B20.8,B20.9,B21,B21.0,B21.1,B21.2,B21.3,B21.7,B21.8,B21.9,B22,B22.0,B22.1,B22.2,B22.7,B23,B23.0,B23.1,B23.2,B23.8,B24",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_34",
        "id_pk": 115,
        "labs_diagnostics": "For adults and children 18 months and older, persons have a positive HIV antibody test (rapid or laboratory-based enzyme immunoassay) confirmed by a second HIV antibody test (rapid or laboratory-based enzyme immunoassay) relying on different antigens or of different operating characteristics. For children younger than 18 months, a positive virological test for HIV or its components (HIV-RNA or HIV-DNA or ultrasensitive HIV p24 antigen) confirmed by a second virological test obtained from a separate determination taken more than 4 weeks after birth.",
        "method": "match",
        "multiple_link": "",
        "name": "HIV",
        "risk_factors": "Unprotected vaginal and/or anal sex, sharing of drug injection equipment, breastfeeding with unknown or HIV-positive status",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Stage 1: \nClinical: Asymptomatic, persistent generalized lymphadenopathy (PGL)\n\nStage 2:\nClinical: Moderate unexplained weight loss (<10% of presumed or measured body weight), recurrent respiratory tract infections (RTIs, sinusitis, bronchitis, otitis media, pharyngitis), herpes zoster, angular cheilitis, recurrent oral ulcerations, papular pruritic eruptions, seborrhoeic dermatitis, fungal nail infections of fingers\n\nStage 3: \nClinical: Severe weight loss (>10% of presumed or measured body weight), unexplained chronic diarrhoea for longer than one month, unexplained persistent fever (intermittent or constant for longer than one month), oral candidiasis, oral hairy leukoplakia, pulmonary tuberculosis diagnosed in last 2 years, severe presumed bacterial infections (e.g. pneumonia, empyema, pyomyositis, bone or joint infection, meningitis, bacteraemia), acute necrotizing ulcerative stomatitis/gingivitis/periodontitis\n\nLab: Unexplained anaemia (<8 g/dl), and/or neutropenia (<500/mm3) and/or thrombocytopenia (<500,000/mm3) for more than one month\n\nStage 4:\nClinical: HIV wasting syndrome, pneumocystis pneumonia, recurrent severe or radiological bacterial pneumonia, chronic herpes simplex infection (orolabial, genital or anorectal of more than one month's duration), oesophageal candidiasis, extrapulmonary TB, kaposi's sarcoma, central nervous system toxoplasmosis, HIV encephalopathy\n\nLab: Extrapulmonary cryptococcosis including meningitis, disseminated non-tuberculous mycobacteria infection, progressive multifocal leukoencephalopathy (PML), candida of trachea/bronchi/lungs, cryptosporidiosis, isosporiasis, visceral herpes simplex infection, cytomegalovirus (CMV) infection (retinitis or of an organ other than liver, spleen or lymph nodes), any disseminated mycosis (e.g. histoplasmosis, coccidiomycosis, penicilliosis), recurrent non-typhoidal salmonella septicaemia, lymphoma (cerebral or B cell non-Hodgkin), invasive cervica carcinoma, visceral leishmaniasis",
        "type": "case"
    },
    "cmd_35": {
        "alert": 0,
        "alert_desc": "Group B",
        "alert_type": "",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description\nAn illness with acute onset of unilateral or bilateral tender, self-limited swelling of the parotid or other salivary gland, lasting 2 days or more, and without other apparent cause. \n\nProbable case  \nA case that meets the clinical description AND has no or non-contributory serologic or virologic testing AND is not epidemiologically linked to a confirmed case. \n\nConfirmed case\nA clinically compatible illness that is EITHER  \n\u2022 Laboratory confirmed; OR \n\u2022 Epidemiologically linked to a confirmed case",
        "category": [
            "cd_tab",
            "Other viral diseases"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "B26,B26.0,B26.1,B26.2,B26.3,B26.8,B26.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_35",
        "id_pk": 116,
        "labs_diagnostics": "Any one of the following:  \n\u2022 Positive serologic test for mumps IgM antibody \n\u2022 \u00e2\u2030\u00a5 four-fold increase in mumps antibody titre \n\u2022 Isolation of mumps virus from a clinical specimen, including throat washings, saliva, urine and cerebrospinal fluid  \n\u2022 PCR positive for mumps virus in clinical specimen ",
        "method": "match",
        "multiple_link": "",
        "name": "Mumps",
        "risk_factors": "Proximity to an infected individual",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Acute onset, unilateral or bilateral tender, self-limited swelling of the parotid or other salivary gland",
        "type": "case"
    },
    "cmd_36": {
        "alert": 0,
        "alert_desc": "None",
        "alert_type": "",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "International Classification of Disease (ICD-10)",
        "category": [
            "cd_tab",
            "Mycoses"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "B35,B35.0,B35.1,B35.2,B35.3,B35.4,B35.5,B35.6,B35.8,B35.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_36",
        "id_pk": 117,
        "labs_diagnostics": "",
        "method": "match",
        "multiple_link": "",
        "name": "Ringworm",
        "risk_factors": "",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "",
        "type": "case"
    },
    "cmd_37": {
        "alert": 0,
        "alert_desc": "Group B",
        "alert_type": "",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description and Probable case\nAn illness with variable signs and symptoms, but most patients experience fever. Other common symptoms include headache, back pain, chills, sweat, myalgia, nausea, vomiting. \n\nConfirmed case  \nA clinically compatible illness with positive laboratory confirmation by blood smear or rapid diagnostic test for malaria",
        "category": [
            "cd_tab",
            "Protozoal diseases"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "B50,B50.0,B50.8,B50.9,B51,B51.0,B51.8,B51.9,B52,B52.0,B52.8,B52.9,B53,B53.0,B53.1,B53.8,B54",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_37",
        "id_pk": 118,
        "labs_diagnostics": "Blood smear or rapid diagnostic malaria test",
        "method": "match",
        "multiple_link": "",
        "name": "Malaria",
        "risk_factors": "Exposure to areas where mosquito vector is present, Stagnant water sources, Movement to/from malaria endemic areas, Children, Pregnant woman, Immune compromised individuals, Malnutrition",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Fever, Anaemia, Single organ failure, Multiple organ failure, Respiratory distress, Chest pain, Severe abdominal pain, Neck pain, Severe headache, Unconscious or repeated convulsions, Compromised circulation",
        "type": "case"
    },
    "cmd_38": {
        "alert": 1,
        "alert_desc": "Group B",
        "alert_type": "threshold:3,5",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description\nVisceral: A person with an illness with prolonged irregular fever, splenomegaly and weight loss as its main symptoms. \n\nCutaneous: A person with the appearance of one or more lesions, typically on uncovered parts of the body such as the face, neck, arms and legs. At the site of inoculation, a nodule appears, which may enlarge to become an indolent ulcer and eventually a depressed scar. In some individuals, certain strains can disseminate and cause mucosal lesions in the nose, throat and mouth cavities (and surrounding tissues).\n\nProbable case  \nA clinically compatible illness.\n\nConfirmed case \n A clinically compatible case that is laboratory confirmed ",
        "category": [
            "cd_tab",
            "Protozoal diseases"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "B55,B55.0,B55.1,B55.2,B55.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_38",
        "id_pk": 119,
        "labs_diagnostics": "Sample take directly from the skin, cultivation by PCR Laboratory test",
        "method": "match",
        "multiple_link": "",
        "name": "Leishmaniasis",
        "risk_factors": "Exposure to sand flies, Malnutrition, Poor housing and sanitation facilities, Population movement",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Lesions on mucous membranes in the nose, mouth, throat cavities and surrounding tissues",
        "type": "case"
    },
    "cmd_39": {
        "alert": 0,
        "alert_desc": "Group B",
        "alert_type": "",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "International Classification of Disease (ICD-10)",
        "category": [
            "cd_tab",
            "Helminthiases"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "B65,B65.0,B65.1,B65.2,B65.3,B65.8,B65.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_39",
        "id_pk": 120,
        "labs_diagnostics": "",
        "method": "match",
        "multiple_link": "",
        "name": "Schistosomiasis",
        "risk_factors": "",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "",
        "type": "case"
    },
    "cmd_4": {
        "alert": 1,
        "alert_desc": "Group A",
        "alert_type": "individual",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description\nA person who ingests food or other agents that causes an infectious or toxic nature primarily of the gastrointestinal tract, but can include other systems (e.g. neurological, immunological). Probable cases have typical clinical symptoms of the illness without laboratory confirmation. Suspected cases have fewer or atypical clinical symptoms.\n\nExclusion: acute watery diarrhea (suspected shigellosis), bloody diarrhea (suspected cholera), acute jaundice syndrome (suspected Hepatitis)\n\nProbable outbreak \nA clinically and epidemiologically compatible illness without laboratory confirmation. \n \nConfirmed outbreak \n A clinically and epidemiologically compatible illness with EITHER  \n\u2022  Laboratory criteria of causative agent; OR \n\u2022 Epidemiological linkage to another confirmed outbreak ",
        "category": [
            "cd_tab",
            "Intestinal infectious diseases"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "A05,A05.0,A05.1,A05.2,A05.3,A05.4,A05.8,A05.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_4",
        "id_pk": 85,
        "labs_diagnostics": "Isolation of suspected causative agent/s (refer to MOH guidelines) AND detailed risk assessment",
        "method": "match",
        "multiple_link": "",
        "name": "Food Poisoning",
        "risk_factors": "Consumption of contaminated food, Consumption of contaminated water",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Nausea, Vomiting, Mucoid diarrhoea (fatty stools), Other diarrhoea (non-watery and non-bloody type), Abdominal pain, Headache, Dizziness, Loss of consciousness, Coma, Thirst, Dehydration, Dyspnoea, Weakness, Malaise, Sore throat, Fever, Chills, Gastroenteritis, Blurred vision, Twitching/convulsions, Tingling/numbness, Dilated pupils, Constricted pupils, Difficulty swallowing/speaking/breathing, Rash, Itching of skin",
        "type": "case"
    },
    "cmd_40": {
        "alert": 0,
        "alert_desc": "None",
        "alert_type": "",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "International Classification of Disease (ICD-10)",
        "category": [
            "cd_tab",
            "Pediculosis",
            "acariasis and other infestations"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "B86",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_40",
        "id_pk": 121,
        "labs_diagnostics": "",
        "method": "match",
        "multiple_link": "",
        "name": "Scabies",
        "risk_factors": "",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "",
        "type": "case"
    },
    "cmd_41": {
        "alert": 0,
        "alert_desc": "None",
        "alert_type": "",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description\nA person with an acute respiratory infection with:\n\u2022 Measured fever >= 38\u00c2\u00b0C; and\n\u2022 Cough; with\n\u2022 Onset within the last 10 days.\n\nProbable case  \nA clinically compatible illness.\n\nConfirmed case \n A clinically compatible case that is laboratory confirmed",
        "category": [
            "cd_tab",
            "Influenza and pneumonia"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "J09,J10,J10.0,J10.1,J10.8,J11,J11.0,J11.1,J11.8",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_41",
        "id_pk": 122,
        "labs_diagnostics": "Conventional or RT \u2022  PCR OR viral antigen detection by immunofluorescence or enzyme immunoassay \nOR viral culture with second identification step to identify influenza viruses \nOR four-fold rise in antibody titre in paired acute and convalescent sera",
        "method": "match",
        "multiple_link": "",
        "name": "Influenza-like illness ",
        "risk_factors": "Person living with HIV, person with active TB, person with other chronic illness, influenza outbreak/seasonal influenza",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Fever, cough, sore throat, runny/stuffy nose, body ache, headache, fatigue, vomiting, diarrhea",
        "type": "case"
    },
    "cmd_42": {
        "alert": 1,
        "alert_desc": "Group A",
        "alert_type": "individual",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description  \nAn acute bacterial disease, characterized by sudden onset of fever (>38.0 degrees Celsius axillary or >38.5 degrees Celsius rectal) AND ONE of the following signs: neck stiffness; altered consciousness; petechial or purpural rash, or other meningeal signs. In children <1 year, meningitis is suspected when fever is accompanied by a bulging fontanelle.\n\nProbable case  \nA clinically compatible illness with Gram-negative diplococci identified in any sterile fluids such as CSF.\n\nConfirmed case \n A clinically compatible case that is laboratory confirmed",
        "category": [
            "cd_tab",
            "Inflammatory diseases of the central nervous system"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "G00",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_42",
        "id_pk": 123,
        "labs_diagnostics": "Conduct lumbar puncture of first 25 cases during an epidemic to confirm diagnosis and serogroup",
        "method": "match",
        "multiple_link": "",
        "name": "Bacterial meningitis",
        "risk_factors": "Close and prolonged contact with individual suspected of having meningitis, High rates of acute respiratory infection (ARI), Overcrowding conditions, Other",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Sudden onset of intense headache, Suddepn onset of fever, Sudden onset of nausea, Sudden onset of vomiting, Sudden onset of photophobia, Sudden onset of stiff neck, Lethargy, Delirium, Coma, Purpura, Shock symptoms, Other",
        "type": "case"
    },
    "cmd_43": {
        "alert": 0,
        "alert_desc": "Group B",
        "alert_type": "",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description  \nAn acute bacterial disease, characterized by sudden onset of fever (>38.0 degrees Celsius axillary or >38.5 degrees Celsius rectal) AND ONE of the following signs: neck stiffness; altered consciousness; petechial or purpural rash, or other meningeal signs. In children <1 year, meningitis is suspected when fever is accompanied by a bulging fontanelle.\n\nProbable case  \nA clinically compatible illness with Gram-negative diplococci identified in any sterile fluids such as CSF.\n\nConfirmed case \n A clinically compatible case that is laboratory confirmed",
        "category": [
            "cd_tab",
            "Inflammatory diseases of the central nervous system"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "G00.0",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_43",
        "id_pk": 124,
        "labs_diagnostics": "Conduct lumbar puncture of first 25 cases during an epidemic to confirm diagnosis and serogroup",
        "method": "match",
        "multiple_link": "",
        "name": "Haemophilus meningitis",
        "risk_factors": "Close and prolonged contact with individual suspected of having meningitis, High rates of acute respiratory infection (ARI), Overcrowding conditions, Other",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Sudden onset of intense headache, Suddepn onset of fever, Sudden onset of nausea, Sudden onset of vomiting, Sudden onset of photophobia, Sudden onset of stiff neck, Lethargy, Delirium, Coma, Purpura, Shock symptoms, Other",
        "type": "case"
    },
    "cmd_44": {
        "alert": 0,
        "alert_desc": "Group B",
        "alert_type": "",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description  \nAn acute bacterial disease, characterized by sudden onset of fever (>38.0 degrees Celsius axillary or >38.5 degrees Celsius rectal) AND ONE of the following signs: neck stiffness; altered consciousness; petechial or purpural rash, or other meningeal signs. In children <1 year, meningitis is suspected when fever is accompanied by a bulging fontanelle.\n\nProbable case  \nA clinically compatible illness with Gram-negative diplococci identified in any sterile fluids such as CSF.\n\nConfirmed case \n A clinically compatible case that is laboratory confirmed",
        "category": [
            "cd_tab",
            "Inflammatory diseases of the central nervous system"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "G00.1,G00.2,G00.3,G00.8,G00.9,G01,G02,G02.0,G02.1,G02.8,G03,G03.0,G03.1,G03.2,G03.8,G03.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_44",
        "id_pk": 125,
        "labs_diagnostics": "Conduct lumbar puncture of first 25 cases during an epidemic to confirm diagnosis and serogroup",
        "method": "match",
        "multiple_link": "",
        "name": "Non-meningicoccal meningitis",
        "risk_factors": "Close and prolonged contact with individual suspected of having meningitis, High rates of acute respiratory infection (ARI), Overcrowding conditions, Other",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Sudden onset of intense headache, Suddepn onset of fever, Sudden onset of nausea, Sudden onset of vomiting, Sudden onset of photophobia, Sudden onset of stiff neck, Lethargy, Delirium, Coma, Purpura, Shock symptoms, Other",
        "type": "case"
    },
    "cmd_45": {
        "alert": 1,
        "alert_desc": "Group B",
        "alert_type": "threshold:3,5,6,10",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "",
        "category": [
            "cd_tab",
            "Injuries to unspecified part of trunk",
            "limb or body region"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "T14.1",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_45",
        "id_pk": 126,
        "labs_diagnostics": "",
        "method": "match",
        "multiple_link": "",
        "name": "Animal Bite",
        "risk_factors": "",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "",
        "type": "case"
    },
    "cmd_46": {
        "alert": 0,
        "alert_desc": "Group B",
        "alert_type": "",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "",
        "category": [
            "cd_tab",
            "Other gastroenteritis and colitis of infectious and unspecified origin"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "A09,A09.0,A09.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_46",
        "id_pk": 127,
        "labs_diagnostics": "",
        "method": "match",
        "multiple_link": "",
        "name": "Diarrhoea",
        "risk_factors": "",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "",
        "type": "case"
    },
    "cmd_47": {
        "alert": 0,
        "alert_desc": "None",
        "alert_type": "",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "",
        "category": [
            "cd_tab"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "U07",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_47",
        "id_pk": 128,
        "labs_diagnostics": "",
        "method": "match",
        "multiple_link": "",
        "name": "Severe Acute Respiratory Illness",
        "risk_factors": "",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "",
        "type": "case"
    },
    "cmd_48": {
        "alert": 1,
        "alert_desc": "Group A",
        "alert_type": "individual",
        "calculation": "",
        "calculation_group": "",
        "calculation_priority": "",
        "case_def": "",
        "category": [
            "cd_tab"
        ],
        "classification": null,
        "classification_casedef": "",
        "condition": "A80.10",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_48",
        "id_pk": 129,
        "labs_diagnostics": "",
        "method": "match",
        "multiple_link": "",
        "name": "Acute Flaccid Paralysis",
        "risk_factors": "",
        "source": "",
        "source_link": "",
        "symptoms": "",
        "type": "case"
    },
    "cmd_5": {
        "alert": 0,
        "alert_desc": "Group B",
        "alert_type": "",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical description  \nTuberculosis (TB) is a chronic bacterial infection characterized pathologically by the formation of granulomas, most common site of infection is the lungs, but other organs may be involved:  \n\u2022 Pulmonary tuberculosis:  Classical symptoms including persistent cough, haemoptysis, afternoon fever, night sweating and weight loss. \n\u2022 Extrapulmonary tuberculosis: Clinical features referable to the respective organ/ system and general well-being affected. \n\nProbable case\nAll cases meeting either the clinical case definition or laboratory criteria, but not the full set of criteria for a confirmed case.   A case meets the following criteria: \n\u2022 Signs and symptoms compatible with active tuberculosis; AND \n\u2022 Supporting evidence from relevant and clinically indicated diagnostic evaluation (e.g., abnormal, unstable [i.e., worsening or improving] chest radiographs); AND \n\u2022 The attending physician forms the opinion that treatment for active tuberculosis with a combination of anti-tuberculosis medications is required  \n\nConfirmed case \nA clinically compatible illness that is laboratory confirmed, or in the absence of laboratory confirmation, a case meeting the clinical case definition and showing an appropriate response to treatment   ",
        "category": [
            "cd_tab",
            "Tuberculosis"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "A15,A15.0,A15.1,A15.2,A15.3,A15.4,A15.5,A15.6,A15.7,A15.8,A15.9,A16,A16.0,A16.1,A16.2,A16.3,A16.4,A16.5,A16.7,A16.8,A16.9,A17,A17.0,A17.1,A17.8,A17.9,A18,A18.0,A18.1,A18.2,A18.3,A18.4,A18.5,A18.6,A18.7,A18.8,A19,A19.0,A19.1,A19.2,A19.8,A19.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_5",
        "id_pk": 86,
        "labs_diagnostics": "3 sputum examined by light microscopic (early morning sample are more likely to contain TB organism)\nOR Chest X-ray",
        "method": "match",
        "multiple_link": "",
        "name": "Tuberculosis",
        "risk_factors": "Crowded living conditions, exposure to someone with known TB, exposure to high prevalence area with TB, HIV-positive",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Cough of long duration (>2 weeks), coughing blood, chest pain, shortness of breath, fever/night sweats, tiredness, loss of appetite, weight loss",
        "type": "case"
    },
    "cmd_6": {
        "alert": 1,
        "alert_desc": "Group A",
        "alert_type": "individual",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description\nA probable case is characterized by fever, chills, headache, malaise, prostration, and leukocytosis that manifests in one or more of the following clinical forms: \n\u2022 Bubonic plague: Regional lymphadenitis \n\u2022 Septicemic plague: Septicemia without an evident bubo  \n\u2022 Pneumonic plague: Primary pneumonic plague:  resulting from inhalation of infectious droplets; Secondary pneumonic plague:  Plague pneumonia, resulting from hematogenous spread in bubonic or septicemic cases       \n\u2022 Pharyngeal plague: Pharyngitis and cervical lymphadenitis resulting from exposure to larger infectious droplets or ingestion of infected tissues \n\nProbable case \n A clinically compatible illness with presumptive laboratory results: \n\u2022 Elevated serum antibody titre to Y. pestis F1 antigen in a patient with no history of plague vaccination; OR  \n\u2022 Detection of Y. pestis F1 antigen in a clinical specimen by fluorescent assay \n\nConfirmed case \n A clinically compatible illness with confirmatory laboratory results.",
        "category": [
            "cd_tab",
            "Certain zoonotic bacterial diseases"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "A20,A20.0,A20.1,A20.2,A20.3,A20.7,A20.8,A20.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_6",
        "id_pk": 87,
        "labs_diagnostics": "Any one of the following:  \n\u2022 Isolation of Yersinia pestis from a clinical specimen \n\u2022 Four-fold or greater change in serum antibody titre to Y. pestis fraction 1 (F1) antigen",
        "method": "match",
        "multiple_link": "",
        "name": "Plague",
        "risk_factors": "Location (endemic rural areas and in urban areas characterized by overcrowding, poor sanitation and a high rat population), occupation (veterinarians)",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "High fever, a painful inflammation and suppuration in the lymph nodes in the area of the bite, headache, vomiting, delirium, shortness of breath, cough, bloody sputum",
        "type": "case"
    },
    "cmd_7": {
        "alert": 1,
        "alert_desc": "Group A",
        "alert_type": "individual",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description\nLocalised form:\n\u2022 Cutaneous: skin lesion evolving over 2 to 6 days from a popular through a vesicular stage, to a depressed black eschar invariably accompanied by oedema that may be mild to extensive.\n\nSystemic form:\n\u2022 Gastrointestinal: abdominal distress characterized by nausea, vomiting, anorexia and followed by fever\n\u2022 Pulmonary: brief prodrome resembling acute viral respiratory illness, followed by rapid onset of hypoxia, dyspnea and high temperature, with X-ray evidence of mediastinal widening\n\u2022 Meningeal: acute onset of high fever possibly with convulsions and loss of consciousness, meningeal signs and symptoms\n\nProbable case\nA person whose case is compatible with the clinical description and has an epidemiological link to confirmed or suspected animal cases or contaminated animal products. \n\nConfirmed case \nA clinically compatible case that is laboratory confirmed.",
        "category": [
            "cd_tab",
            "Certain zoonotic bacterial diseases"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "A22,A22.0,A22.1,A22.2,A22.7,A22.8,A22.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_7",
        "id_pk": 88,
        "labs_diagnostics": "Any one of the following: \n\u2022 Demonstration of Bacillus anthracis in a clinical specimen by microscopic examination of stained smears of vesicular fluid, blood, cerebrospinal fluid, etc \n\u2022 Isolation of Bacillus anthracis from a clinical specimen (e.g. blood, lesions, discharges) \n\u2022 Detection of Bacillus anthracis by nucleic acid testing of a clinical specimen ",
        "method": "match",
        "multiple_link": "",
        "name": "Anthrax",
        "risk_factors": "Skin lesion (cut, abrasion, bite, etc.) that could allow anthrax spore to penetrate, ingestion of contaminated meat, suspected inhalation of anthrax spores",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Cutaneous anthrax: pimple/papule with or without surrounding vesicles, oedema, eschar\n\nGastrointestinal anthrax: nausea, vomiting, fever, abdominal pain, haematemesis, bloody diarrhea, massive ascites, toxaemia and shock, sore throat, dysphagia, fever, regional lymphadenopathy in the neck and toxaemia\n\nPulmonary (inhalation) anthrax: mild fever, fatigue, malaise, headache, muscle ache, chills and fever, dyspnea, cyanosis, disorientation with coma",
        "type": "case"
    },
    "cmd_8": {
        "alert": 1,
        "alert_desc": "Group B",
        "alert_type": "threshold:3,5",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description  \nAn illness characterized by acute or insidious onset, with continued, intermittent or irregular fever of variable duration, profuse sweating particularly at night, fatigue, anorexia, weight loss, headache, arthralgia and generalized aching.  Local infection of various organs may occur. \n\nProbable case\n\u2022 the person who experienced a continuous or intermittent or irregular fever and last for variable periods\n\u2022 the following symptoms: headache, general weakness, profuse perspiration, chills, pain in the joints, depression, weight loss\n\nConfirmed case \nA clinically compatible case that is laboratory confirmed. ",
        "category": [
            "cd_tab",
            "Certain zoonotic bacterial diseases"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "A23,A23.0,A23.1,A23.2,A23.3,A23.8,A23.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_8",
        "id_pk": 89,
        "labs_diagnostics": "Any one of the following: \n\u2022 Isolation of Brucella species from a clinical specimen  \n\u2022 Four-fold or greater rise in Brucella agglutination titre between acute- and convalescent-phase serum specimens ",
        "method": "match",
        "multiple_link": "",
        "name": "Brucellosis",
        "risk_factors": "consumption of unpasteurised goat cheese, occupations who work with animals or come into contact with infected blood  e.g. dairy farmers, slaughterhouse workers",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Headache, general weakness, profuse perspiration, chills, pain in the joints, depression, weight loss",
        "type": "case"
    },
    "cmd_9": {
        "alert": 1,
        "alert_desc": "Group A",
        "alert_type": "individual",
        "calculation": "",
        "calculation_group": "tabs",
        "calculation_priority": "",
        "case_def": "Clinical Description \nLeprosy is a chronic granulomatous infection, primarily affecting skin and peripheral nerves, caused by Mycobacterium leprae.  Clinical forms of leprosy represent a spectrum reflecting the cellular immune response and reaction to M. leprae.  The clinical diagnosis of leprosy is based on the following cardinal signs: anaesthesia, thickened nerves and typical skin lesions. \n \nProbable case \n\u2022 Tuberculoid: one or a few well-demarcated, hypopigmented, and anesthetic skin lesions, frequently with active, spreading edges and a clearing center; peripheral nerve swelling or thickening may also occur \n\u2022 Lepromatous: a number of erythematous papules and nodules or an infiltration of the face, hands, and feet with lesions in a bilateral and symmetrical distribution that progress to thickening of the skin \n\u2022 Borderline (dimorphous): pink lesions characteristic of both the tuberculoid and lepromatous forms \n\u2022 Indeterminate: early lesions, usually hypopigmented macules, without developed tuberculoid or lepromatous features \n\nConfirmed case \nA person with at least two cardinal signs and laboratory confirmed. ",
        "category": [
            "cd_tab",
            "Other bacterial diseases"
        ],
        "classification": null,
        "classification_casedef": "Suspected",
        "condition": "A30,A30.0,A30.1,A30.2,A30.3,A30.4,A30.5,A30.8,A30.9",
        "db_column": "icd_code",
        "disregard": 0,
        "form": "jor_case",
        "id": "cmd_9",
        "id_pk": 90,
        "labs_diagnostics": "\u2022 Multibacillary leprosy: demonstration of acid-fast bacilli in skin or dermal nerve, obtained either by skin biopsy, slit skin smear examination or nerve biopsy of a lepromatous lesion.\n\u2022 Paucibacillary leprosy: characteristic presence of epithelioid cell granulomas within or around peripheral nerves.",
        "method": "match",
        "multiple_link": "",
        "name": "Leprosy",
        "risk_factors": "Close contact with someone with leprosy, Displacement, Overcrowding conditions",
        "source": "International Classification of Disease (ICD-10)",
        "source_link": "http://apps.who.int/classifications/icd10/browse/2015/en",
        "symptoms": "Leprosy patches (can be pale or reddish or copper colored; flat or raised; do not itch; usually do not hurt; lack sensation to heat, touch or pain; can appear anywhere), Reddish or skin-colored nodules, Smooth and shiny diffuse thickening of skin without a loss of sensation, Numbness or tingling of the hands or feet, Weakness of the hands, feet or eyelids, Painful or tender nerves, Swelling of or lumps in the face or earlobes, Painless wounds or burns on the hands or feet",
        "type": "case"
    }
};
